default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: docker
  host: localhost
  port: 5432

development:
  <<: *default
  database: blog-dta_development

test:
  <<: *default
  database: blog-dta_test

production:
  <<: *default
  database: blog-dta_production
  username: postgres
  password: <%= ENV['BLOG-DTA_DATABASE_PASSWORD'] %>
